apiVersion: v1
kind: Service
metadata: 
  name: blockstore-headless
  namespace: goblocks
spec:
  clusterIP: None #This makes it headless
  selector:
    app: blockstore
  ports:
  - port: 6000
    targetPort: 6000
    name: http
